# Here you can specify a default rank.
# Simply add the name of the rank.
# If specified, players will be given this rank when they first join the server.
# For example:
# default-rank: guest
default-rank:

# Here you can add ranks. A typical configuration may look like this: (see below)
# Keep in mind, rank names have to be unique, but rank display names can be different.
# Want to sort ranks? You can add a letter corresponding to the ranks position, as by default, they are sorted alphabetically.
# For example: aowner, badmin, cmember, dguest.
# Don't worry about the names being ugly, they aren't displayed anywhere other than in the command autocomplete, which normal players don't have access to.
#ranks:
#  - name: aowner
#    # Names that will be displayed as prefixes in chat and in the tab-list.
#    display-name: "&4&lOwner" # Dark red and bold.
#    permissions:
#      - worldedit.help
#  - name: badmin
#    display-name: "&c&lAdmin" # Red and bold.
#    permissions:
#      - worldedit.help
#  - name: cmember
#    display-name: Member # White.
#  - name: dguest
#    display-name: "&7Guest" # Grey.
ranks:
